version: '3.9'

services:
  server:
    build: .
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
